apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}-svc
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
spec:
  selector: 
    app: {{ template "observability.label" . }}-{{ template "grafana.label" . }}
{{- if .Values.grafana.service.enabled }}
  type: {{ .Values.grafana.service.type }}
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
