apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.name }}-provider
  namespace: {{ .Values.namespace }}
data:
  #redpandadefault.json: {{ .Files.Get "redpanda-dashboard/redpandadefault.json" | toJson }}
  redpandaops.json: {{ .Files.Get "redpanda-dashboard/redpandaops.json" | toJson }}
  provider.yaml: |-
    apiVersion: 1
    providers:
    - name: 'intverse'
      orgId: 1
      folder: 'Redpanda'
      type: file
      disableDeletion: false
      editable: true
      options:
         path: /etc/grafana/provisioning/dashboards
