apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}-cm
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.prometheus.name }}-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
    - job_name: redpanda
      static_configs:
      - targets:
        - {{ .Values.redpanda_metrics_host }}:9644
      metrics_path: /public_metrics
      tls_config:
        insecure_skip_verify: true
    - job_name: connect
      static_configs:
      - targets:
        - connect:9010
      metrics_path: /
      tls_config:
        insecure_skip_verify: true
