apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}-svc
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
spec:
  selector: 
    app: {{ template "observability.label" . }}-{{ template "prometheus.label" . }}
{{- if .Values.prometheus.service.enabled }}
  type: {{ .Values.prometheus.service.type }}
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
